name: Deploy to Oracle Cloud
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Executar comandos no Servidor via SSH
        uses: appleboy/ssh-action@master
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.CHAVE_ORACLE_NOVA }}
          envs: GROQ_API_KEY
          script: |
            cd /home/ubuntu/projeto-aplicado-uncisal
            git fetch origin
            git reset --hard origin/main
            /home/ubuntu/projeto-aplicado-uncisal/venv/bin/pip install -r requirements.txt
            echo "SECRET_KEY=chave_super_secreta_triatlo_2026" > .env
            echo "GROQ_API_KEY=$GROQ_API_KEY" >> .env
            sudo systemctl restart diario-triatlo.service
            sudo journalctl -u diario-triatlo.service -n 30 --no-pager